version: '3.8'

services:
  # --- 1. ВЕБ-СЕРВЕР (NGINX) ---
  # Входная дверь. Слушает порт 80.
  nginx:
    image: nginx:alpine
    container_name: meest_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static # Раздает статику
    depends_on:
      - web

  # --- 2. ПРИЛОЖЕНИЕ (DJANGO + GUNICORN) ---
  web:
    build: . # Собираем из Dockerfile
    container_name: meest_django
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - static_volume:/app/static # Собирает статику сюда
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq

  # --- 3. ФОНОВЫЙ ВОРКЕР (CELERY) ---
  celery:
    build: . # Тот же образ, что и у web
    container_name: meest_celery
    # Запускаем не Gunicorn, а Celery Worker
    command: celery -A config worker -l info
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis

  # --- 4. БАЗА ДАННЫХ (POSTGRES) ---
  db:
    image: postgres:14
    container_name: meest_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # --- 5. БРОКЕР СООБЩЕНИЙ (RABBITMQ) ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: meest_rabbit
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  # --- 6. КЭШ (REDIS) ---
  redis:
    image: redis:alpine
    container_name: meest_redis
    ports:
      - "6379:6379"

  # --- 7. ELASTICSEARCH (ЛОГИ) ---
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: meest_elastic
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  # --- 8. LOGSTASH (СБОРЩИК) ---
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.9
    container_name: meest_logstash
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch

  # --- 9. KIBANA (ВИЗУАЛИЗАЦИЯ) ---
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: meest_kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  pg_data:
  es_data:
  static_volume: # Том для обмена картинками между Django и Nginx